USE MASTER
GO
IF DB_ID('FLORIST') IS NOT NULL
BEGIN
	DROP DATABASE FLORIST;
END
GO
CREATE DATABASE FLORIST   
GO
USE FLORIST
GO

CREATE TABLE CUSTOMERS 
(
	ID INT IDENTITY(1,1) PRIMARY KEY, 
	FIRST_NAME NVARCHAR(250), 
	LAST_NAME NVARCHAR(250),
	DATE_OF_BIRTH DATETIME,
	GENDER CHAR(10),
	ADDRESS NVARCHAR(4000),
	PHONE_NUMBER INT,
);


CREATE TABLE RECIPIENTS 
(
	ID INT IDENTITY(1,1) PRIMARY KEY, 
	NAME NVARCHAR(250), 
	ADDRESS NVARCHAR(4000),
	PHONE_NUMBER INT,
	DATE DATE,
);
CREATE TABLE BOUQUETS_MESSAGES 
(
	ID INT IDENTITY(1,1) PRIMARY KEY, 
	MESSAGE NVARCHAR(250),
);
CREATE TABLE BOUQUETS 
(
	ID INT IDENTITY(1,1) PRIMARY KEY, 
	NAME NVARCHAR(250), 
	PRICE INT,
	CUSTOMER_ID INT FOREIGN KEY REFERENCES CUSTOMERS(ID),
	RECIPIENT_ID INT FOREIGN KEY REFERENCES RECIPIENTS(ID),
	BOUQUET_MESSAGE_ID INT FOREIGN KEY REFERENCES BOUQUETS_MESSAGES(ID),
);

GO

INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, GENDER, ADDRESS, PHONE_NUMBER) 
VALUES ('Ben','Dover', CAST(N'2021-12-21' AS DateTime),'Business' , 'The Moon', 0123456789);
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, GENDER, ADDRESS, PHONE_NUMBER) 
VALUES ('Mike','Oxlong', CAST(N'2020-02-20' AS DateTime),'Hardcore' , 'The Sun', 0123456789);
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, DATE_OF_BIRTH, GENDER, ADDRESS, PHONE_NUMBER) 
VALUES ('Hugh','Mungus', CAST(N'2019-12-19' AS DateTime),'Death' , 'The Earth', 0123456789);

INSERT INTO RECIPIENTS (NAME, ADDRESS, PHONE_NUMBER, DATE) 
VALUES ('Ben Dover', 'The Moon', 0123456789,  CAST(N'2021-12-21' AS DateTime));
INSERT INTO RECIPIENTS (NAME, ADDRESS, PHONE_NUMBER, DATE) 
VALUES ('Mike Oxlong', 'The Sun', 0123456789, CAST(N'2020-02-20' AS DateTime));
INSERT INTO RECIPIENTS (NAME, ADDRESS, PHONE_NUMBER, DATE) 
VALUES ('Hugh Mungus', 'The Earth', 0123456789, CAST(N'2019-12-19' AS DateTime));

INSERT INTO BOUQUETS_MESSAGES (MESSAGE) 
VALUES ('Happy Birthday!');
INSERT INTO BOUQUETS_MESSAGES (MESSAGE) 
VALUES ('Merry Christmas!');
INSERT INTO BOUQUETS_MESSAGES (MESSAGE) 
VALUES ('Happy New Year!');

INSERT INTO BOUQUETS (NAME, PRICE, CUSTOMER_ID, RECIPIENT_ID, BOUQUET_MESSAGE_ID) 
VALUES ('Chrysanthemum', 0123456789,  1, 1, 1);
INSERT INTO BOUQUETS (NAME, PRICE, CUSTOMER_ID, RECIPIENT_ID, BOUQUET_MESSAGE_ID) 
VALUES ('Rose', 0123456789,  2, 2, 2);
INSERT INTO BOUQUETS (NAME, PRICE, CUSTOMER_ID, RECIPIENT_ID, BOUQUET_MESSAGE_ID) 
VALUES ('Orchid', 0123456789,  3, 3, 3);
